<script>
require([
'jquery'
], function ($) {
$(function () { // to ensure that code evaluates on page load
$(".minus").on("click", function(){
var qty = $(this).closest("div.control").find("input");
var value = Number(qty.val());
if(value > 1) {
value = value - 1;
}
qty.attr('value', value);
})
$(".plus").click(function(){
var qty = $(this).closest("div.control").find("input");
var value = Number(qty.val());
value = value + 1;
qty.attr('value', value);
})
});
});
</script>
<script>
    require([
        'jquery',
        'tabs',
        'slick'
    ], function($) {
        $('.product-items').slick({
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 3,
            arrows:true,
            variableWidth: true,
            responsive: [
            {
                breakpoint: 768,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    infinite: true,
                    arrows: true,
                    variableWidth: false,
                   
                }
            },
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    infinite: true,
                    arrows: true,
                    variableWidth: false,
                }
            },
            {
                breakpoint: 1440,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    infinite: true,
                    arrows: true,
                    variableWidth: false,
                }
            }
            ]
        });
    });
</script>
