<script>
    require([
        'jquery',
        'tabs',
        'slick'
    ], function($) {
        $('.product-items').slick({
            infinite: false,
            slidesToShow: 3,
            slidesToScroll: 3,
            arrows:true,
        });
    });
</script>
<script>
function myFunction() {
  var moreText = document.getElementById("more");
  var btnText = document.getElementById("myBtn");

  if (more.style.display === "none") {
    moreText.style.display = "none";
  } else {
    moreText.style.display = "inline";
    btnText.style.display = "none";
  }
}
</script>
