<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_product')->toHtml(); ?>

<script>
    require([
        'jquery',
        'tabs',
        'slick'
    ], function($) {
        $('.product-items').slick({
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 3,
            arrows:true,
            variableWidth: true,
            responsive: [
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    infinite: true,
                    arrows: true,
                    variableWidth: false,
                   
                }
            },
            {
                breakpoint: 768,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    infinite: true,
                    arrows: true,
                    variableWidth: false,
                   
                }
            },
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    infinite: true,
                    arrows: true,
                    variableWidth: false,
                }
            },
            {
                breakpoint: 1440,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    infinite: true,
                    arrows: true,
                    variableWidth: false,
                }
            }
            ]
        });
    });
</script>